### ISSUE TITLE
Always throws a "aphrodite: command not found" error

### ISSUE THREAD

**Issue by Waltonw59** [AlpinDale/misc-scripts#9]
default settings, it seems to download and install but the command fails to execute with the error,
"/bin/bash: line 1: aphrodite: command not found" then ends execution

**Comment by Waltonw59** [comment]
scratch that I don't think it installed right, I got this output after removing the dev/null output
![Screenshot_20241008_100704_Firefox](https://github.com/user-attachments/assets/cabeb193-934a-4470-b52a-bac9cc4a08a2)

**Comment by BRAIN-IS-BACK** [comment]
I was thinking, "Should I report this error to GitHub?" and was relieved to see that someone else did before me. Now alpin will figure out what's going on.

**Comment by BRAIN-IS-BACK** [comment]
> default settings, it seems to download and install but the command fails to execute with the error, "/bin/bash: line 1: aphrodite: command not found" then ends execution

I was thinking, "Should I report this error to GitHub?" and was relieved to see that someone else did before me. Now alpin will figure out what's going on.

**Comment by AlpinDale** [comment]
Fixed as of 9ecc924
